/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import administrahorarios.*;

/**
 *
 * @author Fauricio
 */
public class CoordinatorWindow extends javax.swing.JFrame {

    /**
     * Creates new form CoordinatorWindow
     */
    public CoordinatorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAddCoordinator = new javax.swing.JMenuItem();
        itemAddProfessor = new javax.swing.JMenuItem();
        itemAddStudent = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemEditCoordinator = new javax.swing.JMenuItem();
        itemEditProfessor = new javax.swing.JMenuItem();
        itemEditStudent = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemDeleteCoordinator = new javax.swing.JMenuItem();
        itemDeleteProfessor = new javax.swing.JMenuItem();
        itemDeleteStudent = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        x.setText("Welcome");

        jMenu1.setText("ADD");

        itemAddCoordinator.setText("COORDINATOR");
        jMenu1.add(itemAddCoordinator);

        itemAddProfessor.setText("PROFESSOR");
        jMenu1.add(itemAddProfessor);

        itemAddStudent.setText("STUDENT");
        jMenu1.add(itemAddStudent);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("EDIT");

        itemEditCoordinator.setText("COORDINATOR");
        itemEditCoordinator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditCoordinatorActionPerformed(evt);
            }
        });
        jMenu2.add(itemEditCoordinator);

        itemEditProfessor.setText("PROFESSOR");
        itemEditProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditProfessorActionPerformed(evt);
            }
        });
        jMenu2.add(itemEditProfessor);

        itemEditStudent.setText("STUDENT");
        jMenu2.add(itemEditStudent);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("DELETE");

        itemDeleteCoordinator.setText("COORDINATOR");
        jMenu5.add(itemDeleteCoordinator);

        itemDeleteProfessor.setText("PROFESSOR");
        jMenu5.add(itemDeleteProfessor);

        itemDeleteStudent.setText("STUDENT");
        jMenu5.add(itemDeleteStudent);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEditProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEditProfessorActionPerformed

    private void itemEditCoordinatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditCoordinatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEditCoordinatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoordinatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoordinatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoordinatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoordinatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoordinatorWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAddCoordinator;
    private javax.swing.JMenuItem itemAddProfessor;
    private javax.swing.JMenuItem itemAddStudent;
    private javax.swing.JMenuItem itemDeleteCoordinator;
    private javax.swing.JMenuItem itemDeleteProfessor;
    private javax.swing.JMenuItem itemDeleteStudent;
    private javax.swing.JMenuItem itemEditCoordinator;
    private javax.swing.JMenuItem itemEditProfessor;
    private javax.swing.JMenuItem itemEditStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
